name = "SpanningSupernet"
uuid = "c92b83c4-19af-4bf9-9c50-c65f2b7803f9"
authors = ["Jake Ireland <jakewilliami@icloud.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
